import type { Metadata } from "next"; 
import "./globals.css";
import ReduxWrapper from "@/lib/redux/ReduxWrapper";
import SessionProviderWrapper from "@/lib/SessionProviderWrapper";
import SessionWatcher from "@/lib/sessionmatcher";
 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <SessionProviderWrapper>
          <ReduxWrapper>
            {children} <SessionWatcher />{" "}
          </ReduxWrapper>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
